[package]
name = "fluxus_key_automation"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.8.4"
reqwest = "0.11.18"
scraper = "0.16.0"
tokio = { version = "1.28.2", features = ["full"] }
